version: '3.8'
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    working_dir: /app
    command: npm start
    environment:
      - PROXY_PORT=8080
      - TARGET_VSCODE_PORT=8000
      - TARGET_VSCODE_HOST=http://serveweb

  serveweb:
    build:
      context: ./serveweb
      dockerfile: Dockerfile.serveweb
    volumes:
      - ./serveweb:/app
    working_dir: /app

  nginx:
    image: nginx:alpine
    ports:
      - "5080:5080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
