version: '3.8'
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    #ports:
      #- "8080:8080"
    volumes:
      - ./proxy:/app
    working_dir: /app
    command: node proxy.js
    depends_on:
      - serveweb

  serveweb:
    build:
      context: ./serveweb
      dockerfile: Dockerfile.serveweb
    #ports:
      #- "8000:8000"
    volumes:
      - ./serveweb:/app
    working_dir: /app

  nginx:
    image: nginx:alpine
    ports:
      - "5080:5080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - proxy
